coverage:
  status:
    project:
      default:
        target: auto
      unit:
        flags: unit
        target: 80
      integration:
        flags: integration
        target: 1
    patch:
      target: 99
parsers:
  javascript:
    enable_partials: yes
