parsers:
  javascript:
    enable_partials: yes
coverage:
  status:
    project:
      default:
        target: 100
      projectA:
        flags: projectA
      projectB:
        target: 50%
        flags: projectB
      unit:
        flags: unit
      integration:
        flags: integration
flags:
  projectA:
    paths:
      - lib/uvm
  projectB:
    paths:
      - lib/
comment: false
