parsers:
  javascript:
    enable_partials: yes
coverage:
  status:
    unit:
      flags: unit
      target: 90
    project:
      default:
        target: auto
      unit:
        flags: unit
        target: 80
      integration:
        flags: integration
